WebServer/config/routes.rb
Rails.application.routes.draw do

  resources :teachers do
    member do
      get 'pageTimetable'
      get 'cv'
      get 'display'
      get 'courses'
    end
  end

  resources :formations

  resources :courses do
    resources :books
    resources :timetables
    resources :teachers
    member do
      get 'pageBook'
      get 'pageTimetable'
      get 'program'
      get 'display'
      get 'pageTeacher'
    end
  end
  resources :formations do
    resources :courses
  end

  get 'welcome/index'
  get 'highschool_info/aboutUs'
  get 'highschool_info/successData'
  get 'highschool_info/theMission'

  root 'welcome#index'

end

WebServer/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    @titre = "All courses"
    @description = "Here, you will find the list of all the Courses available in our High school :"
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @tour = params[:tour]
    @comeFromForm = params[:comeFromForm]
    @titre = @course.title
      if @course.year != nil
        @titre += '('+@course.year+')'
      end
  end

  # GET /courses/new
  def new
    @titre = "New course"
    @course = Course.new
    @course.teachers.build()
  end

  # GET /courses/1/edit
  def edit
    @titre = "Edit "+@course.title
    @teachers = @course.teachers
    @timetables = @course.timetables
    @list_teacher = Teacher.all
  end

  # GET /courses/1/pbook
  def pageBook
    @course = Course.find(params[:id])
    @titre = @course.title
    if @course.year != nil
      @titre += '('+@course.year+')'
    end
  end
  # GET /courses/1/pageTeacher
  def pageTeacher
    @course = Course.find(params[:id])
    @titre = 'The course '+ @course.title + ' is taught by :'
  end
  def pageTimetable
    @course = Course.find(params[:id])
    @titre = @course.title
    if @course.year != nil
      @titre += '('+@course.year+')'
    end
    @list = @course.timetables.to_a.sort_by {|m| [m.day, m.hour]}
  end
  # GET /courses/1/timetable
  # POST /courses
  # POST /courses.json
  def create
    @titre = "Creating a course"
    if params[:formation_id]
      @formation = Formation.find(params[:formation_id])
      @course = @formation.courses.create(course_params)
    else
      @course = Course.new(course_params)
    end
      if @course.save
        redirect_to edit_course_path(@course)
      else
        render 'new'
      end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def display
    @course = Course.find(params[:id])
    @list = params[:act_checkbox]
    @course.teachers.clear
    if @list
      @list.each do |_id,v|
         if v == "1"
           @teacher = Teacher.find(_id)
           @course.teachers<<@teacher
         end
      end
    end
    redirect_to course_path(@course)
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(:title, :desc, :startingHour, :finishHour, :day, :program, :avatar, :avatar_cache, :teachers)
  end
end

WebServer/app/helpers/courses_helper.rb
module CoursesHelper
end

WebServer/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, 'error') %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p class="field">
    <label>Description</label><br>
    <%= f.text_area :desc %>
  </p>
  <p class ="field">
  <label>Avatar of the course</label>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :avatar_cache %>
  </p>
  <p class="field">
    <%= f.label :program %><br>
    <%= f.text_area :program %>
  </p>






    </p>
  <p class="actions">
    <%= f.submit %>
  </p>
<% end %>
</div>

WebServer/app/views/courses/edit.html.erb
<div class = 'col-lg-offset-3'>
  <span class="dropdown">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Edit the timetable<span class="caret"></span></button>
    <ul class="dropdown-menu">
  <% @list = @course.timetables.to_a.sort_by {|m| [m.day, m.hour]}%>
  <% @list.each do |timetable| %>
        <li>
          <strong>Day:</strong>
          <% var= '';
             case timetable.day
               when 0
                 var = 'Monday';
               when 1
                 var = 'Tuesday';
               when 2
                 var = 'Wednesday';
               when 3
                 var = 'Thursday';
               when 4
                 var = 'Friday';
             end
          %>
          <%= var %>
        </li>

        <li>
          <strong>Hour:</strong>
          <%= timetable.hour %>
        </li>

        <li>
          <strong>Room:</strong>
          <%= timetable.room %>
        </li>

        <li>
          <%= link_to 'Destroy Lesson', [timetable.course, timetable],
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </li>
          <li class="divider"></li>
  <% end %>


  <%= form_for([@course, @course.timetables.build]) do |f| %>

        <li>
          <%= f.label :day%><br>
          <%= f.select(:day, options_for_select([['Monday', 0], ['Tuesday', 1], ['Wednesday', 2], ['Thursday', 3], ['Friday', 4]])) %>
        </li>

        <li>
          <%= f.label :hour %><br>
          <%= f.number_field :hour, :min => 8, :max => 17, :value => 8%>
        </li>

        <li>
          <%= f.label :room %><br>
          <%= f.text_field :room %>
        </li>
        <li>
          <%= f.submit %>
        </li>

  <% end %>
    </ul>
    </span>
  <span class="dropdown">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Edit the books<span class="caret"></span></button>
  <ul class="dropdown-menu">
  <% @course.books.each do |book| %>
      <li>
        <strong>Title:</strong>
        <%= book.title %>
      </li>

      <li>
        <strong>Description:</strong>
        <%= book.desc %>

        <%= link_to 'Destroy Book', [book.course, book],
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>

      </li>
        <li class="divider"></li>
  <% end %>

  <%= form_for([@course, @course.books.build]) do |f| %>
      <li>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </li>
      <li>
        <%= f.label :author %><br>
        <%= f.text_field :author %>
      </li>
      <li>
         <%= f.label :town %><br>
         <%= f.text_field :town %>
      </li>
      <li>
         <%= f.label :editor %><br>
         <%= f.text_field :editor %>
      </li>
      <li>
         <%= f.label :collection %><br>
         <%= f.text_field :collection %>
      </li>
      <li>
        <strong>Description:</strong><br>
        <%= f.text_area :desc %>
      </li>
      <li>
        <%= f.label :year %><br>
        <%= f.number_field :year%>
      </li>
      <li>
        <%= f.submit %>
      </li>
  <% end %>
  </ul>
</span>
  <span class="dropdown">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Add/remove teachers<span class="caret"></span></button>
    <ul class="dropdown-menu">
  <form action="display" method="get">
    <% @list_teacher.each do |teacher| %>
        <li>
          <%= check_box(:act_checkbox, teacher.id, {checked:  @course.teachers.exists?(teacher)}) %>
          <%= teacher.name %>
          <%= teacher.firstName %>
        </li>
    <%end%>
   <li> <input type="submit" value="Submit"></li>
  </form>
</ul>
</span>
<%= render 'form' %>

</div>







<%= link_to 'Show', @course %> |
<%= link_to 'Back to All courses', courses_path %>


</div>

WebServer/app/views/courses/index.html.erb
<div class="panel panel-info col-lg-offset-2 col-lg-7">
  <div class="panel-heading">
    <h3 class="panel-title"><%='All courses'%></h3>
  </div>
  <div class="panel-body ">
    <% @courses.each do |course| %>
       <p>
         <strong><%= link_to course.title,course %>
             : </strong>
            <%= course.desc %>
            <%= link_to 'Edit', edit_course_path(course) %>
            <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %>



          </p>
      <% end %>
     </div>
 </div>

WebServer/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

WebServer/app/views/courses/pageBook.html.erb
<div class="col-lg-2">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%=@course.title %></li>
    <li><%= link_to'Description' ,@course %></li>
    <li><%=link_to'Timetable' ,pageTimetable_course_path(params[:id]) %></li>
    <li><%=link_to'Books' ,pageBook_course_path(params[:id]) %></li>
    <li><%=link_to'Programs' , program_course_path(params[:id]) %></li>
    <li class="active"><%="Page related to "+@course.title %></li>
    <li><%= link_to @course.title + '\'s teacher(s)' ,pageTeacher_course_path(params[:id]) %></li>
    <li><%=link_to'Teaching material used in '+@course.title ,'#' %></li>
    <li><%=link_to'Formation containing ' + @course.title ,@course.formation %></li>
    <li><%=link_to'Test and exam' ,'#' %></li>
  </ul>
</div>

<div class="panel panel-info col-lg-7">
  <div class="panel-heading">
    <h3 class="panel-title"><%='Books'%></h3>
  </div>
    <div class="panel-body">
    </div>
<% if @course.books %>
      <h3>Lits of books used in this class: </h3>
      <ul>
<% @course.books.each do |book| %>

    <li>
      <% if !(book.author.blank?) %>
          <strong>
        <%= book.author + ', '  %>
      <% end %>
      <% if !(book.title.blank?) %>
        <%= book.title + ', ' %>
      <% end %>
      <% if !(book.town.blank?) %>
      <%= book.town + ', ' %>
      <% end %>
      <% if !(book.collection.blank?) %>
      <%= book.collection + ', '  %>
      <% end %>
      <% if !(book.year.blank?) %>
      <%= book.year.to_s + ': ' %>
      <% end %>
        </strong>
      <%= book.desc %>
    </li>
<% end %>
      </ul>
      <%end%>


<%= link_to 'Back to all courses', courses_path %>
</div>

WebServer/app/views/courses/pageTeacher.html.erb
<table class = "col-lg-offset-1">
  <thead>
  <tr>
    <th>Firstname</th>
    <th>Name</th>
    <th>Desk</th>
    <th>Phone</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @course.teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.firstName %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.desk %></td>
        <td><%= teacher.phone %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class = "center">
  <button type="button" class="btn btn-default">
<%= link_to "Back",@course%>
    </button>
  </div>

WebServer/app/views/courses/pageTimetable.html.erb
<div class="col-lg-2">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%=@course.title %></li>
    <li><%= link_to'Description' ,@course %></li>
    <li><%=link_to'Timetable' ,pageTimetable_course_path(params[:id]) %></li>
    <li><%=link_to'Books' ,pageBook_course_path(params[:id]) %></li>
    <li><%=link_to'Programs' , program_course_path(params[:id]) %></li>
    <li class="active"><%="Page related to "+@course.title %></li>
    <li><%= link_to @course.title + '\'s teacher(s)' ,pageTeacher_course_path(params[:id]) %></li>
    <li><%=link_to'Teaching material used in '+@course.title ,'#' %></li>
    <li><%=link_to'Formation containing ' + @course.title ,@course.formation %></li>
    <li><%=link_to'Test and exam' ,'#' %></li>
  </ul>
</div>

<div class="panel panel-info col-lg-7">
  <div class="panel-heading">
    <h3 class="panel-title"><%='Timetable'%></h3>
  </div>


  <% @list.each do |timetable| %>

    <p>
      <strong>Day:</strong>
      <% var= '';
         case timetable.day
           when 0
             var = 'Monday';
           when 1
             var = 'Tuesday';
           when 2
             var = 'Wednesday';
           when 3
             var = 'Thursday';
           when 4
             var = 'Friday';
         end
      %>
      <%= var %>
      <strong>Hour: </strong>
      <%= timetable.hour %>
      <strong>Room: </strong>
      <%= timetable.room %>
    </p>
<% end %>


  <%= table_for(@list, :html => {:class => 'center'})  do |t| %>
      <%= t.head do %>
          <%= t.r do %>
              <th class="titre">
                Day
              </th>
              <% (8..18).each do |i| %>
                  <%= t.h(i) %>
              <% end %>
          <% end %>
      <% end %>

      <%= t.body do |timetable| %>
          <%= t.r do %>
              <% var= '';
                 case timetable.day
                   when 0
                     var = 'Monday';
                   when 1
                     var = 'Tuesday';
                   when 2
                     var = 'Wednesday';
                   when 3
                     var = 'Thursday';
                   when 4
                     var = 'Friday';
                 end
              %>
              <%= t.d(h(var)) %>

              <% (8..18).each do |i| %>
                  <% if i != timetable.hour %>
                      <%= t.d('') %>
                  <% else %>
                      <td class="cour">
                        Room: <%= timetable.room %>
                      </td>
                  <% end %>
              <% end %>
          <% end %>
      <% end %>
  <% end %>


<%= link_to 'Back to All courses', courses_path %>
</div>

WebServer/app/views/courses/program.html.erb
<% @course = Course.find(params[:id])
   @titre = @course.title%>
<div class="col-lg-2">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%=@course.title %></li>
    <li><%= link_to'Description' ,@course %></li>
    <li><%=link_to'Timetable' ,pageTimetable_course_path(params[:id]) %></li>
    <li><%=link_to'Books' ,pageBook_course_path(params[:id]) %></li>
    <li><%=link_to'Programs' , program_course_path(params[:id]) %></li>
    <li class="active"><%="Page related to "+@course.title %></li>
    <li><%= link_to @course.title + '\'s teacher(s)' ,pageTeacher_course_path(params[:id]) %></li>
    <li><%=link_to'Teaching material used in '+@course.title ,'#' %></li>
    <li><%=link_to'Formation containing ' + @course.title ,@course.formation %></li>
    <li><%=link_to'Test and exam' ,'#' %></li>
  </ul>
</div>

<div class="panel panel-info col-lg-7">
  <div class="panel-heading">
    <h3 class="panel-title"><%='Program'%></h3>
  </div>
  <div class="panel-body">
    <p> <%= simple_format(@course.program) %> </p>
  </div>

  <%= link_to 'Book', pageBook_course_path(params[:id]) %>
  <%= link_to 'Edit (only for teachers)', edit_course_path(@course) %> |
  <%= link_to 'Back', courses_path %>
</div>

WebServer/app/views/courses/show.html.erb
<div class="col-lg-2">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%=@course.title %></li>
    <li><%= link_to'Description' ,@course %></li>
    <li><%=link_to'Timetable' ,pageTimetable_course_path(params[:id]) %></li>
    <li><%=link_to'Books' ,pageBook_course_path(params[:id]) %></li>
    <li><%=link_to'Programs' , program_course_path(params[:id]) %></li>
    <li class="active"><%="Page related to "+@course.title %></li>
    <li><%= link_to @course.title + '\'s teacher(s)' ,pageTeacher_course_path(params[:id]) %></li>
    <li><%=link_to'Teaching material used in '+@course.title ,'#' %></li>
    <li><%=link_to'Formation containing ' + @course.title ,@course.formation %></li>
    <li><%=link_to'Test and exam' ,'#' %></li>
  </ul>
</div>

<div class="panel panel-info col-lg-7">
  <div class="panel-heading">
    <h3 class="panel-title"><%='Description'%></h3>
  </div>
  <div class="panel-body">
    <p><%= simple_format(@course.desc) %></p>
    <%= image_tag(@course.avatar_url, :alt => @course.title, :align=> "middle", :class => "avatar")%>

    <p>
      <!-- <strong>Day:</strong>
<% var= '';
   case @course.day
     when 0
       var = 'Monday';
     when 1
       var = 'Tuesday';
     when 2
       var = 'Wednesday';
     when 3
       var = 'Thursday';
     when 4
       var = 'Friday';
   end
    %>
<%= var %>



    </p>-->
    <h3> Teachers:</h3>
      <% @course.teachers.each do |teacher| %>
        <p>
          <%= link_to teacher.name + ' ' + teacher.firstName,teacher %>
        </p>
    <%end %>

    <% if @tour!=nil %>

      <div>
        <% if @course.prev!=nil %>
          <img src="/images/arrow_left.png" alt="Left arrow" width="52">
          <%= link_to 'Previous course of the formation: ' + @course.formation.name, course_path(@course.prev,:tour => @tour) %>
        <% end %>
        <% if @course.next!=nil %>
            <div class="right">
              <%= link_to '  Next course of the formation: '  + @course.formation.name, course_path(@course.next,:tour => @tour) %>
              <img src="/images/arrow_right.png" alt="Left arrow" width="52">
            </div>
        <% end %>
      </div>

    <% end %>
    <% if @comeFromForm!=nil %>
        <%= link_to 'Back to formation: '  + @course.formation.name, @course.formation %> |
    <% end %>
    <%= link_to 'Back to All Courses', courses_path %> |
    <%= link_to 'Edit this page (only for teachers)', edit_course_path(@course) %>

  </div>
</div>

WebServer/app/views/courses/timetable.html.erb
<% @course = Course.find(params[:id])
   @titre = @course.title%>
<div class="col-lg-2">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%=@course.title %></li>
    <li><%= link_to'Description' ,@course %></li>
    <li><%=link_to'Timetable' ,timetable_course_path(params[:id]) %></li>
    <li><%=link_to'Books' ,'#' %></li>
    <li><%=link_to'Programs' , program_course_path(params[:id]) %></li>
    <li class="active"><%="Page related to "+@course.title %></li>
    <li><%= link_to'Teacher teaching '+@course.title ,'#' %></li>
    <li><%=link_to'Teaching material used in '+@course.title ,'#' %></li>
    <li><%=link_to'Formation containing ' +@course.title ,@course.formation %></li>
    <li><%=link_to'Test and exam' ,'#' %></li>
  </ul>
</div>

<div class="panel panel-info col-lg-7">
  <div class="panel-heading">
    <h3 class="panel-title"><%='Timetable'%></h3>
  </div>
  <div class="panel-body">
    <p><%= @course.desc %></p>
  </div>
<!--
  <p>
    <strong>Day:</strong>
    <% var= '';
       case @course.day
         when 0
           var = 'Monday';
         when 1
           var = 'Tuesday';
         when 2
           var = 'Wednesday';
         when 3
           var = 'Thursday';
         when 4
           var = 'Friday';
       end
    %>
    <%= var %>
  </p>
-->
  <%= link_to 'Book', pageBook_course_path(params[:id]) %>
  <%= link_to 'Edit (only for teachers)', edit_course_path(@course) %> |
  <%= link_to 'Back', courses_path %>