WebServer/config/routes.rb
Rails.application.routes.draw do

  resources :teachers do
    member do
      get 'pageTimetable'
      get 'cv'
      get 'display'
      get 'courses'
    end
  end

  resources :formations

  resources :courses do
    resources :books
    resources :timetables
    resources :teachers
    member do
      get 'pageBook'
      get 'pageTimetable'
      get 'program'
      get 'display'
      get 'pageTeacher'
    end
  end
  resources :formations do
    resources :courses
  end

  get 'welcome/index'
  get 'highschool_info/aboutUs'
  get 'highschool_info/successData'
  get 'highschool_info/theMission'

  root 'welcome#index'

end

WebServer/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    @titre = 'Welcome !'

end

WebServer/app/helpers/welcome_helper.rb
module WelcomeHelper
  @title='Welcome!'
end

WebServer/app/views/welcome/index.html.erb
<body>
<div class="container-fluid">
  <div class="panel panel-info">
    <div class="panel-heading">Shortcuts:</div>
      <div class="panel-body center ">
        <p>
        <%= link_to "All formations: Here is the guide of all formations available here", formations_path, class: "btn btn-large btn-primary" %>
        <%= link_to "All teachers", teachers_path, class: "btn btn-large btn-primary" %>
        <%= link_to "Abouts Us: If you want to know more about our history and our traditions", highschool_info_aboutUs_path, class: "btn btn-large btn-primary" %>
        </p>
      </div>
  </div>
</div>

<div class = "center">
<%= image_tag("banner4.jpg", :alt => "main image", :align=> "middle") %>
</div>
</body>