WebServer/config/routes.rb
Rails.application.routes.draw do

  resources :teachers do
    member do
      get 'pageTimetable'
      get 'cv'
      get 'display'
      get 'courses'
    end
  end

  resources :formations

  resources :courses do
    resources :books
    resources :timetables
    resources :teachers
    member do
      get 'pageBook'
      get 'pageTimetable'
      get 'program'
      get 'display'
      get 'pageTeacher'
    end
  end
  resources :formations do
    resources :courses
  end

  get 'welcome/index'
  get 'highschool_info/aboutUs'
  get 'highschool_info/successData'
  get 'highschool_info/theMission'

  root 'welcome#index'

end

WebServer/app/models/formation.rb
class Formation < ActiveRecord::Base
  has_many :courses
  validates :name, presence: true,
            length: { minimum: 5 }

end

WebServer/app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :set_formation, only: [:show, :edit, :update, :destroy]

  # GET /formations
  # GET /formations.json
  def index
    @formations = Formation.all
    @titre = "Field of formation"
    @description = "You can get all the courses which belong to the following formation:"
  end

  # GET /formations/1
  # GET /formations/1.json
  def show
    @titre = 'Courses for '+@formation.name+' formation.'
    @description = 'Here, you have the list of all the courses that are possible to do in the '+@formation.name+' formation.'
  end

  # GET /formations/new
  def new
    @titre = 'New formation'
    @formation = Formation.new
  end

  # GET /formations/1/edit
  def edit
    @titre = 'Editing formation'
  end

  # POST /formations
  # POST /formations.json
  def create

    @formation = Formation.new(formation_params)

    respond_to do |format|
      if @formation.save
        format.html { redirect_to @formation, notice: 'Formation was successfully created.' }
        format.json { render :show, status: :created, location: @formation }
      else
        format.html { render :new }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1
  # PATCH/PUT /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to @formation, notice: 'Formation was successfully updated.' }
        format.json { render :show, status: :ok, location: @formation }
      else
        format.html { render :edit }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1
  # DELETE /formations/1.json
  def destroy
    @formation.destroy
    respond_to do |format|
      format.html { redirect_to formations_url, notice: 'Formation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formation_params
      params.require(:formation).permit(:name)
    end
end

WebServer/app/helpers/formations_helper.rb
module FormationsHelper
end

WebServer/app/views/formations/_form.html.erb
<%= form_for(@formation) do |f| %>
  <% if @formation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formation.errors.count, "error") %> prohibited this formation from being saved:</h2>

      <ul>
      <% @formation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WebServer/app/views/formations/edit.html.erb
<div class = 'col-lg-offset-3'>
<%= render 'form' %>
<form role="form">
  <div class="form-group">
<%= link_to 'Show', @formation %> |
<%= link_to 'Back', formations_path %>
  </div>
 </form>
</div>

WebServer/app/views/formations/index.html.erb
<div class="row">
<div class="panel panel-info col-lg-offset-2 col-lg-7">
  <div class="panel-heading">
    <h3 class="panel-title"><%='Formations'%></h3>
  </div>
  <div class="panel-body ">
    <% @formations.each do |formation| %>
        <p><strong><%=link_to formation.name, formation %></strong>
        <%= link_to 'Edit', edit_formation_path(formation) %>
        <%= link_to 'Destroy', formation, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</div>
</div>
</div>
<p>

<%= link_to 'New Formation', new_formation_path %>
</p>

WebServer/app/views/formations/new.html.erb
<div class = 'col-lg-offset-3'>

<%= render 'form' %>

<%= link_to 'Back', formations_path %>
</div>

WebServer/app/views/formations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="panel panel-success col-lg-offset-2 col-lg-7">
      <div class="panel-heading">
        <h3 class="panel-title">Guided tour</h3>
      </div>
      <div class="panel-body">
        <p> <%=link_to 'Start a tour of all the courses of the '+@formation.name+ ' formation', course_path(@formation.courses.first, :tour => @formation.name) %></p>
      </div>
    </div>
</div>
<div class="row">
    <div class="panel panel-info col-lg-offset-2 col-lg-7">
      <div class="panel-heading">
        <h3 class="panel-title"><%='Courses of the '+@formation.name+ ' formation'%></h3>
      </div>
      <div class="panel-body">
        <% @formation.courses.each do |course| %>
            <p>
              <%= link_to course.title, course_path(course, :comeFromForm => @formation.name) %>
              <strong> : </strong>
              <%= course.desc %>
            </p>
        <% end %>
      </div>
    </div>
</div>
<div class = "center">
<h2>Add a course:</h2>
<%= form_for([@formation, @formation.courses.build]) do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :desc %><br>
      <%= f.text_area :desc %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
</div>
<%= link_to 'Edit', edit_formation_path(@formation) %> |
<%= link_to 'Back', formations_path %>